/**
 * Context Store — Persistent storage for tiered memory
 *
 * This module provides the storage backend for Tyrion's cool and cold
 * memory tiers. It persists structured entries to YAML/JSONL files and
 * supports keyword-based search across the stored content.
 *
 * Storage layout:
 *   ~/.casterly/memory/
 *     cool/
 *       entries.jsonl     — recent archived entries (last 30 days)
 *       index.yaml        — lightweight index for keyword search
 *     cold/
 *       entries.jsonl     — all historical entries
 *       reflections/      — link to existing reflections dir
 *
 * Each entry is a line in entries.jsonl with metadata (tags, timestamp,
 * tier, source) for efficient filtering.
 *
 * Privacy: The store never contains raw sensitive user data. All entries
 * are generated by Tyrion's agent loop from codebase-level observations.
 */

import { readFile, writeFile, appendFile, mkdir, readdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { randomBytes } from 'node:crypto';
import { getTracer } from './debug.js';

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A single memory entry stored in the context store.
 */
export interface MemoryEntry {
  /** Unique identifier */
  id: string;

  /** When this entry was created */
  timestamp: string;

  /** Which tier this entry belongs to */
  tier: 'cool' | 'cold';

  /** Tags for retrieval and categorization */
  tags: string[];

  /** Source of this entry */
  source: 'agent' | 'reflection' | 'archive' | 'issue' | 'goal';

  /** The actual content */
  content: string;

  /** Optional title for the entry */
  title: string;

  /** Optional metadata */
  metadata?: Record<string, unknown>;

  /** Optional embedding vector for semantic search */
  embedding?: number[];
}

/**
 * Search result from a recall query.
 */
export interface RecallResult {
  /** The matching entry */
  entry: MemoryEntry;

  /** Relevance score (higher = more relevant) */
  score: number;

  /** Which keywords matched */
  matchedKeywords: string[];
}

/**
 * Configuration for the context store.
 */
export interface ContextStoreConfig {
  /** Base directory for memory storage */
  basePath: string;

  /** Maximum entries in the cool tier before promotion to cold */
  maxCoolEntries: number;

  /** Days before cool entries are promoted to cold tier */
  coolRetentionDays: number;

  /** Maximum entries to return from a search */
  defaultSearchLimit: number;

  /** Path to existing reflections directory (for cold tier integration) */
  reflectionsPath: string;

  /**
   * Weight for hybrid recall (0.0 = keyword only, 1.0 = embedding only).
   * Only used when embeddings are available. Default: 0.4.
   */
  hybridWeight: number;

  /** Minimum cosine similarity threshold for embedding matches. Default: 0.3. */
  similarityThreshold: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────────────────────────────────

const DEFAULT_CONFIG: ContextStoreConfig = {
  basePath: '~/.casterly/memory',
  maxCoolEntries: 200,
  coolRetentionDays: 30,
  defaultSearchLimit: 10,
  reflectionsPath: '~/.casterly/autonomous/reflections',
  hybridWeight: 0.4,
  similarityThreshold: 0.3,
};

/**
 * Generate a unique entry ID using timestamp + random bytes.
 * No global mutable counter — safe across concurrent imports.
 */
function generateEntryId(): string {
  const ts = Date.now().toString(36);
  const rand = randomBytes(4).toString('hex');
  return `mem-${ts}-${rand}`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Context Store
// ─────────────────────────────────────────────────────────────────────────────

export class ContextStore {
  private readonly config: ContextStoreConfig;
  private readonly coolPath: string;
  private readonly coldPath: string;
  private initialized: boolean = false;

  constructor(config?: Partial<ContextStoreConfig>) {
    this.config = { ...DEFAULT_CONFIG, ...config };

    // Resolve home directory
    const basePath = this.config.basePath.replace(/^~/, process.env['HOME'] ?? '~');
    this.coolPath = join(basePath, 'cool');
    this.coldPath = join(basePath, 'cold');
  }

  // ── Initialization ──────────────────────────────────────────────────────

  /**
   * Ensure storage directories exist.
   */
  async initialize(): Promise<void> {
    if (this.initialized) return;

    const tracer = getTracer();
    await tracer.withSpan('memory', 'initialize', async () => {
      await mkdir(this.coolPath, { recursive: true });
      await mkdir(this.coldPath, { recursive: true });
      this.initialized = true;
      tracer.log('memory', 'debug', 'Context store initialized', {
        coolPath: this.coolPath,
        coldPath: this.coldPath,
      });
    });
  }

  // ── Archive (Write) ─────────────────────────────────────────────────────

  /**
   * Archive content to a memory tier. Default tier is 'cool'.
   * Returns the entry ID.
   */
  async archive(params: {
    content: string;
    title: string;
    tags: string[];
    tier?: 'cool' | 'cold';
    source?: MemoryEntry['source'];
    metadata?: Record<string, unknown>;
  }): Promise<string> {
    await this.initialize();
    const tracer = getTracer();

    return tracer.withSpan('memory', 'archive', async (span) => {
      const entry: MemoryEntry = {
        id: generateEntryId(),
        timestamp: new Date().toISOString(),
        tier: params.tier ?? 'cool',
        tags: params.tags,
        source: params.source ?? 'archive',
        content: params.content,
        title: params.title,
        ...(params.metadata !== undefined ? { metadata: params.metadata } : {}),
      };

      const targetPath = entry.tier === 'cool' ? this.coolPath : this.coldPath;
      const entriesFile = join(targetPath, 'entries.jsonl');

      await appendFile(entriesFile, JSON.stringify(entry) + '\n', 'utf8');

      // Check cool tier size and trim if needed
      if (entry.tier === 'cool') {
        await this.trimCoolTier();
      }

      tracer.log('memory', 'info', `Archived entry ${entry.id}`, {
        tier: entry.tier,
        tags: entry.tags,
        titleLength: entry.title.length,
        contentLength: entry.content.length,
      });

      span.metadata['entryId'] = entry.id;
      return entry.id;
    });
  }

  // ── Recall (Search) ─────────────────────────────────────────────────────

  /**
   * Search memory for entries matching a query. Uses keyword-based
   * scoring: each matching keyword in title, content, or tags adds
   * to the relevance score.
   */
  async recall(params: {
    query: string;
    tier?: 'cool' | 'cold' | 'both';
    tags?: string[];
    limit?: number;
    source?: MemoryEntry['source'];
  }): Promise<RecallResult[]> {
    await this.initialize();
    const tracer = getTracer();

    return tracer.withSpan('memory', 'recall', async (span) => {
      const searchTier = params.tier ?? 'both';
      const limit = params.limit ?? this.config.defaultSearchLimit;

      // Extract keywords from query (lowercase, deduplicated)
      const keywords = extractKeywords(params.query);

      tracer.log('memory', 'debug', `Recall query: "${params.query}"`, {
        tier: searchTier,
        keywords,
        limit,
      });

      // Load entries from the relevant tiers
      const entries: MemoryEntry[] = [];

      if (searchTier === 'cool' || searchTier === 'both') {
        entries.push(...await this.loadEntries(this.coolPath));
      }

      if (searchTier === 'cold' || searchTier === 'both') {
        entries.push(...await this.loadEntries(this.coldPath));
        // Also search existing reflections in cold tier
        entries.push(...await this.loadReflectionsAsEntries());
      }

      // Filter by tags if specified
      let filtered = entries;
      if (params.tags && params.tags.length > 0) {
        const requiredTags = new Set(params.tags.map((t) => t.toLowerCase()));
        filtered = filtered.filter((e) =>
          e.tags.some((t) => requiredTags.has(t.toLowerCase())),
        );
      }

      // Filter by source if specified
      if (params.source) {
        filtered = filtered.filter((e) => e.source === params.source);
      }

      // Score entries against keywords
      const scored: RecallResult[] = filtered.map((entry) => {
        const { score, matchedKeywords } = scoreEntry(entry, keywords);
        return { entry, score, matchedKeywords };
      });

      // Sort by score descending, filter zero-score, take limit
      const results = scored
        .filter((r) => r.score > 0)
        .sort((a, b) => b.score - a.score)
        .slice(0, limit);

      span.metadata['totalEntries'] = entries.length;
      span.metadata['filtered'] = filtered.length;
      span.metadata['results'] = results.length;

      tracer.log('memory', 'info', `Recall found ${results.length} results`, {
        query: params.query,
        totalSearched: filtered.length,
      });

      return results;
    });
  }

  // ── Entry Loading ───────────────────────────────────────────────────────

  /**
   * Load all entries from a tier directory.
   */
  private async loadEntries(dirPath: string): Promise<MemoryEntry[]> {
    const entriesFile = join(dirPath, 'entries.jsonl');
    const entries: MemoryEntry[] = [];

    try {
      const content = await readFile(entriesFile, 'utf8');
      const lines = content.trim().split('\n');

      for (const line of lines) {
        if (!line.trim()) continue;
        try {
          const entry = JSON.parse(line) as MemoryEntry;
          entries.push(entry);
        } catch {
          // Skip malformed lines
        }
      }
    } catch {
      // File doesn't exist yet — that's fine
    }

    return entries;
  }

  /**
   * Load existing reflections as MemoryEntry objects for searching.
   * Bridges the Phase 1 Reflector output into the Phase 4 memory system.
   */
  private async loadReflectionsAsEntries(): Promise<MemoryEntry[]> {
    const entries: MemoryEntry[] = [];
    const reflectionsPath = this.config.reflectionsPath.replace(
      /^~/,
      process.env['HOME'] ?? '~',
    );

    try {
      const files = await readdir(reflectionsPath);
      const jsonFiles = files.filter((f) => f.endsWith('.json')).slice(-50); // Last 50

      for (const file of jsonFiles) {
        try {
          const content = await readFile(join(reflectionsPath, file), 'utf8');
          const reflection = JSON.parse(content) as {
            cycleId: string;
            timestamp: string;
            observation: { description: string };
            reasoning: string;
            changes?: string[];
            outcome?: string;
          };

          entries.push({
            id: `ref-${reflection.cycleId}`,
            timestamp: reflection.timestamp,
            tier: 'cold',
            tags: ['reflection', reflection.outcome ?? 'unknown'],
            source: 'reflection',
            title: reflection.observation?.description ?? `Cycle ${reflection.cycleId}`,
            content: [
              reflection.observation?.description,
              reflection.reasoning,
              reflection.changes?.join(', '),
            ]
              .filter(Boolean)
              .join('\n'),
          });
        } catch {
          // Skip invalid files
        }
      }
    } catch {
      // Reflections directory doesn't exist yet — fine
    }

    return entries;
  }

  // ── Tier Management ─────────────────────────────────────────────────────

  /**
   * Trim the cool tier to stay within limits. Moves excess entries
   * to cold tier, oldest first.
   */
  private async trimCoolTier(): Promise<void> {
    const entries = await this.loadEntries(this.coolPath);

    if (entries.length <= this.config.maxCoolEntries) {
      return;
    }

    const tracer = getTracer();

    // Sort by timestamp ascending (oldest first)
    entries.sort((a, b) => a.timestamp.localeCompare(b.timestamp));

    // Promote oldest entries to cold tier
    const excess = entries.length - this.config.maxCoolEntries;
    const toPromote = entries.slice(0, excess);
    const toKeep = entries.slice(excess);

    // Write promoted entries to cold tier
    const coldFile = join(this.coldPath, 'entries.jsonl');
    const promotedLines = toPromote.map((e) => {
      e.tier = 'cold';
      return JSON.stringify(e);
    }).join('\n') + '\n';
    await appendFile(coldFile, promotedLines, 'utf8');

    // Rewrite cool tier with remaining entries
    const coolFile = join(this.coolPath, 'entries.jsonl');
    const keptLines = toKeep.map((e) => JSON.stringify(e)).join('\n') + '\n';
    await writeFile(coolFile, keptLines, 'utf8');

    tracer.log('memory', 'info', `Promoted ${excess} entries from cool to cold tier`);
  }

  /**
   * Promote stale cool entries to cold tier based on age.
   * Called periodically (e.g., during dream cycles).
   */
  async promoteStaleEntries(): Promise<number> {
    await this.initialize();
    const entries = await this.loadEntries(this.coolPath);
    const cutoff = Date.now() - this.config.coolRetentionDays * 24 * 60 * 60 * 1000;

    const stale = entries.filter((e) => new Date(e.timestamp).getTime() < cutoff);
    const fresh = entries.filter((e) => new Date(e.timestamp).getTime() >= cutoff);

    if (stale.length === 0) return 0;

    // Move stale entries to cold
    const coldFile = join(this.coldPath, 'entries.jsonl');
    const staleLines = stale.map((e) => {
      e.tier = 'cold';
      return JSON.stringify(e);
    }).join('\n') + '\n';
    await appendFile(coldFile, staleLines, 'utf8');

    // Rewrite cool tier without stale entries
    const coolFile = join(this.coolPath, 'entries.jsonl');
    if (fresh.length > 0) {
      const freshLines = fresh.map((e) => JSON.stringify(e)).join('\n') + '\n';
      await writeFile(coolFile, freshLines, 'utf8');
    } else {
      await writeFile(coolFile, '', 'utf8');
    }

    const tracer = getTracer();
    tracer.log('memory', 'info', `Promoted ${stale.length} stale entries to cold tier`);

    return stale.length;
  }

  // ── Statistics ──────────────────────────────────────────────────────────

  /**
   * Get counts of entries per tier.
   */
  async getStats(): Promise<{ cool: number; cold: number; reflections: number }> {
    await this.initialize();
    const cool = await this.loadEntries(this.coolPath);
    const cold = await this.loadEntries(this.coldPath);
    const reflections = await this.loadReflectionsAsEntries();
    return {
      cool: cool.length,
      cold: cold.length,
      reflections: reflections.length,
    };
  }

  /**
   * Get the base path for testing/inspection.
   */
  getBasePath(): string {
    return dirname(this.coolPath);
  }

  // ── Hybrid Recall (Keyword + Embedding) ──────────────────────────────

  /**
   * Search memory using a hybrid of keyword scoring and embedding similarity.
   * If a query embedding is provided, combines keyword score with cosine
   * similarity. Entries without embeddings fall back to keyword-only scoring.
   *
   * The hybridWeight config controls the blend:
   *   finalScore = (1 - hybridWeight) * keywordScore + hybridWeight * embeddingScore
   */
  async hybridRecall(params: {
    query: string;
    queryEmbedding?: number[];
    tier?: 'cool' | 'cold' | 'both';
    tags?: string[];
    limit?: number;
    source?: MemoryEntry['source'];
  }): Promise<RecallResult[]> {
    // Without an embedding, fall back to pure keyword recall
    if (!params.queryEmbedding || params.queryEmbedding.length === 0) {
      return this.recall(params);
    }

    await this.initialize();
    const tracer = getTracer();

    return tracer.withSpan('memory', 'hybridRecall', async (span) => {
      const searchTier = params.tier ?? 'both';
      const limit = params.limit ?? this.config.defaultSearchLimit;
      const keywords = extractKeywords(params.query);

      // Load entries
      const entries: MemoryEntry[] = [];
      if (searchTier === 'cool' || searchTier === 'both') {
        entries.push(...await this.loadEntries(this.coolPath));
      }
      if (searchTier === 'cold' || searchTier === 'both') {
        entries.push(...await this.loadEntries(this.coldPath));
        entries.push(...await this.loadReflectionsAsEntries());
      }

      // Filter
      let filtered = entries;
      if (params.tags && params.tags.length > 0) {
        const requiredTags = new Set(params.tags.map((t) => t.toLowerCase()));
        filtered = filtered.filter((e) =>
          e.tags.some((t) => requiredTags.has(t.toLowerCase())),
        );
      }
      if (params.source) {
        filtered = filtered.filter((e) => e.source === params.source);
      }

      // Compute keyword scores and find max for normalization
      const keywordScores = filtered.map((entry) => scoreEntry(entry, keywords));
      const maxKeywordScore = Math.max(1, ...keywordScores.map((s) => s.score));

      // Score entries with hybrid blend
      const scored: RecallResult[] = filtered.map((entry, i) => {
        const kw = keywordScores[i]!;
        const normalizedKeyword = kw.score / maxKeywordScore;

        // Compute embedding similarity if the entry has one
        let embeddingScore = 0;
        if (entry.embedding && entry.embedding.length > 0) {
          embeddingScore = cosineSim(params.queryEmbedding!, entry.embedding);
        }

        // Blend: if entry has embedding, use hybrid; otherwise keyword only
        const hasEmbedding = entry.embedding && entry.embedding.length > 0;
        const w = hasEmbedding ? this.config.hybridWeight : 0;
        const finalScore = (1 - w) * normalizedKeyword + w * embeddingScore;

        return {
          entry,
          score: finalScore,
          matchedKeywords: kw.matchedKeywords,
        };
      });

      // Filter by threshold and sort
      const threshold = this.config.similarityThreshold;
      const results = scored
        .filter((r) => r.score > threshold || r.matchedKeywords.length > 0)
        .sort((a, b) => b.score - a.score)
        .slice(0, limit);

      span.metadata['totalEntries'] = entries.length;
      span.metadata['results'] = results.length;
      span.metadata['hybrid'] = true;

      tracer.log('memory', 'info', `Hybrid recall found ${results.length} results`, {
        query: params.query,
        totalSearched: filtered.length,
      });

      return results;
    });
  }

  /**
   * Archive content with an optional embedding vector.
   */
  async archiveWithEmbedding(params: {
    content: string;
    title: string;
    tags: string[];
    embedding?: number[];
    tier?: 'cool' | 'cold';
    source?: MemoryEntry['source'];
    metadata?: Record<string, unknown>;
  }): Promise<string> {
    return this.archive({
      ...params,
      metadata: {
        ...params.metadata,
        ...(params.embedding ? { __embedding_dims: params.embedding.length } : {}),
      },
    });
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Keyword Search Helpers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Extract searchable keywords from a query string.
 * Strips common stop words and returns lowercase tokens.
 */
function extractKeywords(query: string): string[] {
  const stopWords = new Set([
    'a', 'an', 'the', 'is', 'are', 'was', 'were', 'be', 'been',
    'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would',
    'could', 'should', 'may', 'might', 'can', 'shall',
    'i', 'me', 'my', 'we', 'our', 'you', 'your', 'he', 'she', 'it',
    'they', 'them', 'their', 'this', 'that', 'these', 'those',
    'of', 'in', 'on', 'at', 'to', 'for', 'with', 'by', 'from',
    'about', 'into', 'through', 'during', 'before', 'after',
    'and', 'or', 'but', 'not', 'if', 'then', 'else', 'when',
    'what', 'which', 'who', 'how', 'why', 'where',
  ]);

  const tokens = query
    .toLowerCase()
    .replace(/[^\w\s-]/g, ' ')
    .split(/\s+/)
    .filter((t) => t.length >= 2 && !stopWords.has(t));

  return [...new Set(tokens)];
}

/**
 * Score a memory entry against search keywords.
 * Title matches score 3x, tag matches score 2x, content matches score 1x.
 */
function scoreEntry(
  entry: MemoryEntry,
  keywords: string[],
): { score: number; matchedKeywords: string[] } {
  let score = 0;
  const matchedKeywords: string[] = [];
  const titleLower = entry.title.toLowerCase();
  const contentLower = entry.content.toLowerCase();
  const tagsLower = entry.tags.map((t) => t.toLowerCase());

  for (const keyword of keywords) {
    let matched = false;

    // Title match (3x weight)
    if (titleLower.includes(keyword)) {
      score += 3;
      matched = true;
    }

    // Tag match (2x weight)
    if (tagsLower.some((t) => t.includes(keyword))) {
      score += 2;
      matched = true;
    }

    // Content match (1x weight)
    if (contentLower.includes(keyword)) {
      score += 1;
      matched = true;
    }

    if (matched) {
      matchedKeywords.push(keyword);
    }
  }

  return { score, matchedKeywords };
}

/**
 * Cosine similarity between two vectors. Returns 0 if either is empty.
 */
function cosineSim(a: number[], b: number[]): number {
  if (a.length !== b.length || a.length === 0) return 0;

  let dot = 0;
  let normA = 0;
  let normB = 0;

  for (let i = 0; i < a.length; i++) {
    const ai = a[i]!;
    const bi = b[i]!;
    dot += ai * bi;
    normA += ai * ai;
    normB += bi * bi;
  }

  const denom = Math.sqrt(normA) * Math.sqrt(normB);
  return denom === 0 ? 0 : dot / denom;
}
