/**
 * Project Store — Manages the `projects/<slug>/` convention and PROJECT.md metadata.
 *
 * Each code project (game, app, tool, website) generated by DeepLoop lives
 * in its own subfolder under `<projectRoot>/projects/<slug>/`.  A `PROJECT.md`
 * file inside each folder records the goal, architecture, file list, plan
 * steps, and a running history of work done on the project.
 *
 * See docs/dual-loop-architecture.md Phase 5.
 */

import { readFile, readdir, stat } from 'node:fs/promises';
import { join, basename } from 'node:path';
import { safeWriteFile } from '../persistence/safe-write.js';
import type { FileOperation, PlanStep } from './task-board-types.js';

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A discovered project found by scanning `projects/`.
 */
export interface DiscoveredProject {
  slug: string;
  projectDir: string;  // Relative path, e.g. "projects/neon-invaders"
  goal: string;
  status: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// slugify
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Convert a project name into a kebab-case slug suitable for directory names.
 *
 * Rules:
 *  - Lowercase
 *  - Replace non-alphanumeric chars with hyphens
 *  - Collapse consecutive hyphens
 *  - Trim leading/trailing hyphens
 *  - Max 40 characters
 */
export function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/-{2,}/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 40);
}

// ─────────────────────────────────────────────────────────────────────────────
// detectProjectDir
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Inspect a workspace manifest and detect the project directory.
 *
 * Filters for paths starting with `projects/`, extracts the `projects/<slug>`
 * prefix, and returns it if consistent across all matching entries.
 * Returns `null` if no `projects/` paths are found or if there are
 * conflicting project directories.
 */
export function detectProjectDir(manifest: FileOperation[]): string | null {
  const projectPrefixes = new Set<string>();

  for (const file of manifest) {
    const match = /^(projects\/[^/]+)/.exec(file.path);
    if (match?.[1]) {
      projectPrefixes.add(match[1]);
    }
  }

  // Must be exactly one consistent project directory
  if (projectPrefixes.size === 1) {
    return [...projectPrefixes][0]!;
  }

  return null;
}

// ─────────────────────────────────────────────────────────────────────────────
// discoverProjects
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Scan `<projectRoot>/projects/` for subdirectories containing a PROJECT.md.
 *
 * Reads each PROJECT.md and extracts the Goal and Status lines via regex.
 * Returns an empty array if the `projects/` directory doesn't exist.
 */
export async function discoverProjects(projectRoot: string): Promise<DiscoveredProject[]> {
  const projectsDir = join(projectRoot, 'projects');
  const results: DiscoveredProject[] = [];

  let entries: string[];
  try {
    entries = await readdir(projectsDir);
  } catch {
    // projects/ doesn't exist yet — that's fine
    return [];
  }

  for (const entry of entries) {
    const entryPath = join(projectsDir, entry);

    // Only look at directories
    try {
      const info = await stat(entryPath);
      if (!info.isDirectory()) continue;
    } catch {
      continue;
    }

    // Try to read PROJECT.md
    const mdPath = join(entryPath, 'PROJECT.md');
    let content: string;
    try {
      content = await readFile(mdPath, 'utf8');
    } catch {
      continue; // No PROJECT.md — skip
    }

    // Extract Goal and Status lines
    const goalMatch = /^##?\s*Goal\s*\n+(.+)/mi.exec(content);
    const statusMatch = /^##?\s*Status\s*\n+(.+)/mi.exec(content);

    results.push({
      slug: entry,
      projectDir: `projects/${entry}`,
      goal: goalMatch?.[1]?.trim() ?? '(unknown)',
      status: statusMatch?.[1]?.trim() ?? '(unknown)',
    });
  }

  return results;
}

// ─────────────────────────────────────────────────────────────────────────────
// writeProjectMd
// ─────────────────────────────────────────────────────────────────────────────

export interface WriteProjectMdParams {
  projectRoot: string;
  projectDir: string;           // e.g. "projects/neon-invaders"
  isUpdate: boolean;            // true = append history, false = fresh write
  originalMessage?: string;
  plan?: string;
  planSteps?: PlanStep[];
  manifest?: FileOperation[];
  userFacing?: string;
  taskId?: string;
}

/**
 * Write or update the PROJECT.md file for a project.
 *
 * Fresh write: Creates a full PROJECT.md with Goal, Status, Architecture,
 * Files, Plan Steps, Known Issues, and History sections.
 *
 * Update: Reads the existing file, updates the Status and Updated timestamp,
 * and appends a History entry with the task summary.
 */
export async function writeProjectMd(params: WriteProjectMdParams): Promise<void> {
  const mdPath = join(params.projectRoot, params.projectDir, 'PROJECT.md');
  const slug = basename(params.projectDir);
  const now = new Date().toISOString();

  if (params.isUpdate) {
    await updateExistingProjectMd(mdPath, params, now);
  } else {
    await writeFreshProjectMd(mdPath, slug, params, now);
  }
}

// ── Internal helpers ──────────────────────────────────────────────────────────

function writeFreshProjectMd(
  mdPath: string,
  slug: string,
  params: WriteProjectMdParams,
  now: string,
): Promise<void> {
  const title = slug
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');

  const sections: string[] = [];

  sections.push(`# ${title}\n`);

  // Goal
  sections.push('## Goal\n');
  sections.push(params.originalMessage ?? '(no description provided)');
  sections.push('');

  // Status
  sections.push('## Status\n');
  sections.push('Initial implementation complete');
  sections.push('');

  // Timestamps
  sections.push('## Metadata\n');
  sections.push(`- **Created:** ${now}`);
  sections.push(`- **Updated:** ${now}`);
  if (params.taskId) {
    sections.push(`- **Last Task:** ${params.taskId}`);
  }
  sections.push('');

  // Architecture (from plan)
  if (params.plan) {
    sections.push('## Architecture\n');
    sections.push(params.plan);
    sections.push('');
  }

  // Files
  if (params.manifest && params.manifest.length > 0) {
    sections.push('## Files\n');
    for (const file of params.manifest) {
      const lineInfo = file.lines !== undefined ? ` (${file.lines} lines)` : '';
      sections.push(`- \`${file.path}\` — ${file.action}${lineInfo}`);
    }
    sections.push('');
  }

  // Plan Steps
  if (params.planSteps && params.planSteps.length > 0) {
    sections.push('## Plan Steps\n');
    for (const step of params.planSteps) {
      const icon = step.status === 'done' ? '[x]' : '[ ]';
      sections.push(`- ${icon} ${step.description}`);
    }
    sections.push('');
  }

  // Known Issues (empty to start)
  sections.push('## Known Issues\n');
  sections.push('(none yet)');
  sections.push('');

  // History
  sections.push('## History\n');
  const summary = params.userFacing ?? params.originalMessage ?? 'Initial implementation';
  const stepCount = params.planSteps?.length ?? 0;
  sections.push(`- **${now}** — ${summary} (${stepCount} steps)`);
  sections.push('');

  return safeWriteFile(mdPath, sections.join('\n'));
}

async function updateExistingProjectMd(
  mdPath: string,
  params: WriteProjectMdParams,
  now: string,
): Promise<void> {
  let content: string;
  try {
    content = await readFile(mdPath, 'utf8');
  } catch {
    // File doesn't exist despite isUpdate — fall back to fresh write
    const slug = basename(mdPath.replace('/PROJECT.md', ''));
    return writeFreshProjectMd(mdPath, slug, params, now);
  }

  // Update the "Updated" timestamp
  content = content.replace(
    /^- \*\*Updated:\*\* .+$/m,
    `- **Updated:** ${now}`,
  );

  // Update the "Last Task" line (or add it)
  if (params.taskId) {
    if (/^- \*\*Last Task:\*\*/.test(content)) {
      content = content.replace(
        /^- \*\*Last Task:\*\* .+$/m,
        `- **Last Task:** ${params.taskId}`,
      );
    } else {
      content = content.replace(
        /^- \*\*Updated:\*\* .+$/m,
        (match) => `${match}\n- **Last Task:** ${params.taskId}`,
      );
    }
  }

  // Update the Status section
  content = content.replace(
    /^(## Status\n\n?)(.+)$/m,
    `$1Continued work — see History`,
  );

  // Update the Files section if we have a new manifest
  if (params.manifest && params.manifest.length > 0) {
    const newFileLines = params.manifest
      .map((f) => {
        const lineInfo = f.lines !== undefined ? ` (${f.lines} lines)` : '';
        return `- \`${f.path}\` — ${f.action}${lineInfo}`;
      })
      .join('\n');

    // Try to replace existing Files section
    const filesRegex = /^## Files\n\n([\s\S]*?)(?=\n## |\n*$)/m;
    if (filesRegex.test(content)) {
      // Merge: keep existing entries, add new ones
      const existingMatch = filesRegex.exec(content);
      const existingFiles = existingMatch?.[1] ?? '';
      const existingPaths = new Set(
        [...existingFiles.matchAll(/`([^`]+)`/g)].map((m) => m[1]),
      );
      const additions = params.manifest
        .filter((f) => !existingPaths.has(f.path))
        .map((f) => {
          const lineInfo = f.lines !== undefined ? ` (${f.lines} lines)` : '';
          return `- \`${f.path}\` — ${f.action}${lineInfo}`;
        });

      if (additions.length > 0) {
        content = content.replace(
          filesRegex,
          (match) => `${match.trimEnd()}\n${additions.join('\n')}\n`,
        );
      }
    } else {
      // No existing Files section — add before History
      content = content.replace(
        /^## History/m,
        `## Files\n\n${newFileLines}\n\n## History`,
      );
    }
  }

  // Append a History entry
  const summary = params.userFacing ?? params.originalMessage ?? 'Continued work';
  const stepCount = params.planSteps?.length ?? 0;
  const historyEntry = `- **${now}** — ${summary} (${stepCount} steps)`;

  if (/^## History/m.test(content)) {
    // Append to end of History section
    content = content.trimEnd() + `\n${historyEntry}\n`;
  } else {
    // No History section — add one
    content = content.trimEnd() + `\n\n## History\n\n${historyEntry}\n`;
  }

  await safeWriteFile(mdPath, content);
}
